services:
  strm_watch:
    image: ghcr.io/zaiwuli/strm_watch:latest
    container_name: strm_watch
    restart: always
    ports:
      - "8501:8501"
    environment:
      - SOURCE_DIR=/source
      - TARGET_DIR=/target
    volumes:
      - "/volume3/媒体库/云盘:/source"
      - "/volume3/Media/网盘/ceshi:/target"
      - "./strm_config:/config"
